Move config to di instead of di-web
yiisoft/assets pull request #135
Opened 2024-01-15 14:03 UTC by Gerych1984

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #132

2024-01-15 15:52 UTC, xepozz commented
Moving di-web to di means you want to have it also in console runs. Is it so? What use case do you have?

2024-01-16 10:31 UTC, samdark approved these changes

2024-01-20 10:47 UTC, vjik requested changes
Looks good 👍
Need line in changelog only

2024-01-20 10:47 UTC, vjik commented on .github/workflows/bc.yml
> +        ['8.1', '8.2', '8.3']
```suggestion
        ['8.0']
```

2024-01-20 10:47 UTC, vjik commented on .github/workflows/build.yml
> +        ['8.1', '8.2', '8.3']
```suggestion
        ['8.0', '8.1', '8.2', '8.3']
```

2024-01-20 10:47 UTC, vjik commented on .github/workflows/composer-require-checker.yml
> +        ['8.1', '8.2', '8.3']
```suggestion
        ['8.0', '8.1', '8.2', '8.3']
```

2024-01-20 10:47 UTC, vjik commented on .github/workflows/mutation.yml
> +        ['8.1', '8.2', '8.3']
```suggestion
        ['8.3']
```

2024-01-20 10:47 UTC, vjik commented on .github/workflows/static.yml
> +        ['8.1', '8.2', '8.3']
```suggestion
        ['8.0', '8.1', '8.2', '8.3']
```

2024-01-22 08:13 UTC, Gerych1984 commented
> Looks good 👍 Need line in changelog only

Done

2024-01-22 10:52 UTC, vjik approved these changes

2024-01-22 15:07 UTC, samdark approved these changes

2024-01-22 15:08 UTC, merged

2024-01-22 15:08 UTC, samdark commented
👍