Translation into Brazilian Portuguese and corrections to the documentation in English.
yiisoft/assets pull request #140
Opened 2024-04-11 15:39 UTC by luizcmarin

Note the following:
- created folders according to the standard for documentation
- all links checked
- in the asset-manager.md file, on line 186 "[`config/web.php`](../config/web.php)" the file does not exist. I changed it to "[`config/web.php`](../../../config/di.php)" because this file exists.

2024-04-12 10:56 UTC, vjik requested changes
Need fix links to doc files in README

2024-04-12 10:56 UTC, vjik commented on docs/guides/en/asset-converter.md
> +Below we're using bootstrap bundle from [Asset bundles](asset-bundles.md) guide:
Keep quotes

2024-04-12 10:56 UTC, vjik commented on docs/guides/en/asset-manager.md
> +For general usage see [asset bundles](asset-bundles.md). In this guide we'll focus on configuring it.
Keep quotes

2024-04-20 13:54 UTC, samdark commented on README.md
> +- More information can be found in the [Internals.](docs/internals.md)
```suggestion
- [Internals](docs/internals.md)
```

2024-04-23 11:50 UTC, merged